# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanJi',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125, verbose_name='班级')),
            ],
            options={
                'verbose_name_plural': '班级',
                'verbose_name': '班级',
            },
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(verbose_name='班级人数')),
                ('xuexiwy', models.CharField(blank=True, max_length=123, null=True, verbose_name='学习委员')),
                ('shenghuowy', models.CharField(blank=True, max_length=123, null=True, verbose_name='生活委员')),
                ('tiyuwy', models.CharField(blank=True, max_length=123, null=True, verbose_name='体育委员')),
                ('wenyiwy', models.CharField(blank=True, max_length=123, null=True, verbose_name='文艺委员')),
                ('desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('banji', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.BanJi', verbose_name='班级')),
            ],
            options={
                'verbose_name_plural': '班级信息',
                'verbose_name': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, verbose_name='课程名')),
            ],
            options={
                'verbose_name_plural': '课程',
                'verbose_name': '课程',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, verbose_name='名字')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('desc', models.CharField(default='默认描述。。。', max_length=1024, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('banji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.BanJi', verbose_name='所属班级')),
            ],
            options={
                'verbose_name_plural': '学生',
                'verbose_name': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, verbose_name='名字')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('introduce', models.CharField(blank=True, max_length=2560, null=True, verbose_name='教师介绍')),
                ('desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('in_time', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('out_time', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('classes', models.ManyToManyField(blank=True, null=True, to='app01.Course', verbose_name='所教课程')),
            ],
            options={
                'verbose_name_plural': '教师',
                'verbose_name': '教师',
            },
        ),
        migrations.AddField(
            model_name='classinfo',
            name='banzhuren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Teacher', verbose_name='班主任'),
        ),
    ]
